spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://github.com/CrazySpringCloud/sc-f-chapter6
          # 配置仓库路径
          search-paths: respo
          # 访问git仓库的用户名（如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写）
          username:
          # 访问git仓库的用户密码
          password:
      # 配置仓库的分支
      label: master
server:
  port: 8888
